### ISSUE TITLE
剩余模块

### ISSUE THREAD

**Issue by PassionZale** [PassionZale/iMall#2]
### 订单模块
最近忙于房贷申请，后期将陆续增加后台CMS订单功能模块编写。

**Comment by wdjwxh** [comment]
辛苦， 写的真好用，昨天帮别人搭了个简易的~

**Comment by PassionZale** [comment]
现在还没有对接微信支付，因为手上暂时还没有已开通微信支付的服务号给我做测试。

这套源码只是实现了最基础的商城功能，再往后会重开一个新的分支使用vue，vuex重构整个项目增加额外的新功能

1. 商品多规格；
2. 三级代理返佣；
3. 会员积分；
4. 商品评论；
5. 促销活动（满减优惠券）等。

**Comment by wdjwxh** [comment]
我以前给别人做过微信支付，现在在学习vue，需要的话我也可以帮忙一起写

**Comment by PassionZale** [comment]
hah,可以的呀,后面第二个branch我也准备拉点人来一起贡献代码。

**Comment by cqllang** [comment]
目前vue.js 2.0已经出来很久了，有否考虑把vue.js升级为2.x?
@PassionZale

**Comment by PassionZale** [comment]
@cqllang 现在公司项目比较紧，最近一段时间肯能没太多时间写。
这个项目主要以学习为主，后面我会再升级成2.x的，谢谢建议！

**Comment by jackylee1** [comment]
> 现在还没有对接微信支付，因为手上暂时还没有已开通微信支付的服务号给我做测试。
> 
> 这套源码只是实现了最基础的商城功能，再往后会重开一个新的分支使用vue，vuex重构整个项目增加额外的新功能
> 
> 1. 商品多规格；
> 2. 三级代理返佣；
> 3. 会员积分；
> 4. 商品评论；
> 5. 促销活动（满减优惠券）等。

请问啥时候继续这些新功能呢
