### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by lizilong007** [PassionZale/iMall#4]
你好，为啥你的个人类型的公众帐号，没有微信认证，确可以调用获取用户信息的接口。是有啥方法嘛，求解。感谢🙏

**Comment by PassionZale** [comment]
你好，你说的“个人类型公众账号”，是指iMall里面用的这种测试接口号吧？

测试接口号本来就由获取粉丝信息的接口权限。

它没有微信支付权限，
模板消息需要在后台自己拼接模板，其他获取access_token，地理位置，粉丝信息等都是和认证订阅号或服务号一样的。

你可以自己申请一个接口号，在接口权限里面查看相关详情：
[微信公众平台接口测试帐号申请](https://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=sandbox/login)

**Comment by PassionZale** [comment]
当然测试接口号还有很多其他限制，如：
@lizilong007 
- 无法根据名称被搜索到，只能通过二维码识别才能添加测试号
- 粉丝列表最大为100，超过100，微信服务器不再推送subscribe 等事件
- 所有接口的调用，前提是粉丝已关注测试号，包括做静默授权或非静默授权的网页登录等

**Comment by lizilong007** [comment]
哦。原来是这样，明白了，感谢回答。
