### ISSUE TITLE
路由访问的问题

### ISSUE THREAD

**Issue by wploey** [PassionZale/iMall#5]
前后端有各自的路由,访问不存在的路由时报错能怎么优化下吗.最近在做类似这种项目,微信授权时由后端路由控制授权,到前端时,有点绕不过来,大神有点什么思路提供下没

**Comment by wploey** [comment]
再看下你的代码, 我有点思路了,加多一个前缀跟路由正则匹配下就行

**Comment by PassionZale** [comment]
抱歉，最近公司工作量略大，今早才看到这条 issue。
是这样的，对整个 webapp 来讲，路由都是由服务端控制的。
整个前端，是一个 SPA，由 Laravel 的 router 进行授权或其他操作后，渲染这个 SPA 的 .html 文件。
如果你要加其他的业务逻辑，也可以在 Laravel 加多一个路由，然后在 SPA 中加一个路由，做完你需要的业务逻辑判断（如授权，等）后，服务端可以将当前请求重定向到你的 SPA 任意路由。

**Comment by PassionZale** [comment]
很抱歉，我暂时已经没有精力继续迭代这个项目了。
这个项目暂时没有接入微信支付，如果你还遇到其他问题，[希望这个链接可以帮助你。](https://github.com/Chooin/wechat-spa)
当然也可以继续提一些 issues 给我 ：）
